### ISSUE TITLE
Not Working with PHP latest version (7.1)

### ISSUE THREAD

**Issue by Sunilthecoder007** [softon/indipay#35]
its not working with latest version of php i.e. 7.1 i tried with 7.0 and its working fine ,,,this is the error i get with php 7.1 "**Function mcrypt_module_open() is deprecated**"

**Comment by dbhosale** [comment]
please try this package dbhosale/indipay .I have fixed the mcrypt issue for php7.1

**Comment by gopal-g** [comment]
@dbhosale  I am using your package i still get the same error and i also happen to check the code under the encrypt method it still uses `mcrypt_module_open` with a `@` operator at the beginning which just suppresses the error/warning but is not a real fix for the issue.

**Comment by softon** [comment]
This cannot be resolved from our side. CCAvenue should modify their code to remove the deprecated functions the appropriate changes can be done.

**Comment by gopal-g** [comment]
Yes thats correct, I have raised a ticket in CCavenue and waiting almost for 2 months now they said they are trying to develop a SDK kit for PHP7.1. Poor development team ever.

**Comment by gopal-g** [comment]
### Update 

CCavenue has released their latest SDK for the same now we are able to integrate it on PHP 7.1 you can use my own package for the same [gopal-g/payment](https://github.com/gopal-g/payment). It is very much similar to this package.
